# Generated by Django 2.2.5 on 2020-07-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_address_id',
            field=models.CharField(max_length=50, null=True, verbose_name='地址id'),
        ),
    ]
